@TodoAPI_HostAddress = https://localhost:7183

POST {{TodoAPI_HostAddress}}/register
Content-Type: application/json

{
  "email": "alice@email.com",
  "password": "Abcd1!"
}
###

POST {{TodoAPI_HostAddress}}/login
Content-Type: application/json

{
  "email": "bob@email.com",
  "password": "Abcd1!"
}
###

